### ISSUE TITLE
Migration to ROS-2

### ISSUE THREAD

**Issue by padhupradheep** [neobotix/neo_localization2#1]
Distributions to be served:

- [x] Rolling (Development)

- [x] Galactic (Recommended)

- [ ] Foxy

**Comment by HappySamuel** [comment]
Hi

For compiling neo_localization2 onto ROS2 Foxy, just need to edit 1 file `neo_localization2/include/neo_localization/Convert.h`
Change the following
``` #include <tf2_geometry_msgs/tf2_geometry_msgs.hpp> ```
to
``` #include <tf2_geometry_msgs/tf2_geometry_msgs.h> ```
After that, do `colcon build --symlink-install`

Already tested compiling and running it on ROS2 Foxy. Hope this can help those who want to run neo_localization2 on Foxy.

Best,
Samuel

**Comment by padhupradheep** [comment]
Awesome, if anyone wants to use Foxy feel free to use the solution given by Samuel. 

No further steps is needed. Closing imminent!
