### ISSUE TITLE
Tile map frame not set

### ISSUE THREAD

**Issue by automech-rb** [neobotix/neo_localization2#16]
Hi,

I am not able to view topic map_tile in Rviz2 (shows no frame id error). I suspect the error is due to no header / frame set for this [msg](https://github.com/neobotix/neo_localization2/blob/aeed20fcf29d9f8a32520eecadebb6ba164c1768/src/neo_localization_node.cpp#L651).

Please let me know if I am wrong.

Thanks

**Comment by padhupradheep** [comment]
You are right. Feel free to open a PR, if you would like to contribute. Else, I can do the update!

**Comment by padhupradheep** [comment]
Okay I did the changes pointing to the main branch. I will do the sync to humble and galactic soon.

**Comment by automech-rb** [comment]
Thank you.

**Comment by padhupradheep** [comment]
No problem! 

Will close the issue, once sync is done.
