### ISSUE TITLE
no contents on branch foxy

### ISSUE THREAD

**Issue by fmros** [neobotix/neo_localization2#21]
This repository does not contain anything on branch "foxy" expcept the Readme.

**Comment by padhupradheep** [comment]
Hey, unfortunately, we do not support Foxy, since the packages surrounding it are much better in Galactic / Humble. 

I would suggest you to either move to Galactic or Humble.

**Comment by fmros** [comment]
Ok, then I would delete this branch since it might lead to confusion.

Thanks

**Comment by padhupradheep** [comment]
Sure!
