### ISSUE TITLE
Question: Detecting divergence

### ISSUE THREAD

**Issue by automech-rb** [neobotix/neo_localization2#24]
Hi,

As the title suggest, I would like to detect when localization is lost (diverged).
Something like a confidence in current estimate.

Do you have any recommended variable in current implementation which 
shows confidence in the localization.

Thanks.

**Comment by padhupradheep** [comment]
Hi, 

Good question, we already have a confidence score, see [here](https://github.com/neobotix/neo_localization2/blob/rolling/src/neo_localization_node.cpp#L492). You just need to set the `m_broadcast_info` parameter to `true` in order for you to know about the confidence. 

At the moment, the logs will appear after every 10 cycles of the localization node. In case, if you want to see the score at a specific interval, we could also set it up. 

Hope it helps!

**Comment by automech-rb** [comment]
Thank you!
