### ISSUE TITLE
Building error: neo_localization/Convert.h:14:10: fatal error: tf2_geometry_msgs/tf2_geometry_msgs.hpp: No such file

### ISSUE THREAD

**Issue by ljaniec** [neobotix/neo_localization2#4]
Hello,

Details:
* Ubuntu 20.04, ROS Galactic

* I wanted to build locally your package and I got this error:

```
ljaniec@ljaniec-PC:~/ros2_ws$ colcon build --symlink-install --packages-select neo_localization2 
Starting >>> neo_localization2
--- stderr: neo_localization2                             
In file included from /home/ljaniec/ros2_ws/src/neo_localization2/src/neo_localization_node.cpp:10:
/home/ljaniec/ros2_ws/src/neo_localization2/include/neo_localization/Convert.h:14:10: fatal error: tf2_geometry_msgs/tf2_geometry_msgs.hpp: No such file or directory
   14 | #include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/neo_localization_node.dir/build.make:63: CMakeFiles/neo_localization_node.dir/src/neo_localization_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/neo_localization_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< neo_localization2 [1.05s, exited with code 2]
```
I have `tf2` packages installed through `apt`, I tried to build the whole `geometry2` metapackage in the same workspace too, but it didn't help.

**Comment by padhupradheep** [comment]
Please checkout to the correct branch and retry! Thanks!

**Comment by ljaniec** [comment]
The package was built correctly after checkout to Galactic branch, but the end result which I wanted to achieve (starting multi-robot simulation with Nav2) wasn't possible - the simulation hanged there. 
Where should I issue logs and a description of these new problems? 
Is there any README for setting up your ROS2 multi-AMR Nav2 simulation?

**Comment by padhupradheep** [comment]
>  Is there any README for setting up your ROS2 multi-AMR Nav2 simulation?

Unfortunately, the navigation stack for the multi-AMR Nav2 simulation is not available at the moment. It is still in a developmental phase. You need to follow this [branch](https://github.com/neobotix/neo_simulation2/tree/feature/multi_robot_navigation) for further updates.  

In case if there is any feature, that you would like to see in neo_simulation2, apart from the multi-robot navigation, please feel to open an issue in that repository. 

May I know is there any specific use-case you are targeting?

**Comment by ljaniec** [comment]
Thank you, I will observe any details on mentioned branch.

I am developing a hybrid controllers for multiple mobile robot systems, based on two layers of control, discrete and continuous-time. Until now my simulations were really simplified, but the end goal is to have real industrial robots instead of simulated agent under control. Similar research/software development is conducted there: https://github.com/open-rmf/rmf_ros2

My specific use-case is a group of AMRs on the known map, receiving orders from centralized controller with optimized, simultaneous motion without collision and deadlocks (correct-by-build type of formal logic control). I hoped to use your project at the base for a simulated environment and a pair of AMRs to initial tests of implemented solution.

**Comment by HappySamuel** [comment]
#1

Hi @ljaniec 

If you're still facing issue of building neo_localization2 onto ROS2 foxy, you may reference to the solution i found.

Best,
Samuel

**Comment by padhupradheep** [comment]
Thanks! Feel free to reopen, if you guys have any issues!
